### PR TITLE
add save CSV control to health app. update doc and screenshots

### PR DESCRIPTION
**Pull request by flatearth-hadella**
Added 'Save CSV?' checkbox to the Health app. Also update the docs with an example of saved CSV data and updated the screenshots.

### CODE REVIEW

**Review by flatearth-tidd — APPROVED** [review]
User guide looks good. Once the zip has been updated, downloaded directly from S3 and tested by someone, @dack-fe or @fe-wickham, let's move forward with merge.

**Review by dack-fe — APPROVED** [review]
Everything looks good and the S3 file has been updated

**Comment by flatearth-tidd** [comment]
@dack-fe did you quickly test the app downloaded from S3?

**Comment by dack-fe** [comment]
@flatearth-tidd Yes. I did a download and test from S3

**Pull request merged**
